# Generated by Django 4.2.7 on 2023-11-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_description',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_difficulty',
            field=models.CharField(default='Beginner', max_length=1000),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_duration',
            field=models.CharField(default='1', max_length=1000),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
